export const exerciseDatabase: Record<string, { id: string; name: string; type: string }[]> = {
  CHEST: [
    { id: 'bb_flat', name: 'Flat Barbell Bench Press', type: 'Compound movement' },
    { id: 'bb_inc', name: 'Incline Barbell Bench Press', type: 'Compound movement' },
    { id: 'bb_dec', name: 'Decline Barbell Bench Press', type: 'Compound movement' },
    { id: 'db_flat', name: 'Flat Dumbbell Bench Press', type: 'Compound movement' },
    { id: 'db_inc', name: 'Incline Dumbbell Bench Press', type: 'Compound movement' },
    { id: 'db_dec', name: 'Decline Dumbbell Bench Press', type: 'Compound movement' },
    { id: 'ch_cp_1', name: 'Machine Chest Press', type: 'Compound movement' },
    { id: 'ch_cp_2', name: 'Incline Machine Press', type: 'Compound movement' },
    { id: 'ch_cp_3', name: 'Smith Machine Flat Press', type: 'Compound movement' },
    { id: 'ch_cp_4', name: 'Smith Machine Incline Press', type: 'Compound movement' },
    { id: 'ch_cp_5', name: 'Floor Press', type: 'Compound movement' },
    { id: 'ch_cp_6', name: 'Spoto Press', type: 'Compound movement' },
    { id: 'ch_cp_7', name: 'Guillotine Press', type: 'Compound movement' },
    { id: 'ch_cp_8', name: 'Push-Ups', type: 'Compound movement' },
    { id: 'ch_cp_9', name: 'Weighted Push-Ups', type: 'Compound movement' },
    { id: 'ch_cp_10', name: 'Dips (Chest Focus)', type: 'Compound movement' },
    { id: 'ch_cp_11', name: 'Weighted Dips', type: 'Compound movement' },
    { id: 'ch_cp_12', name: 'Plyometric Push-Ups', type: 'Compound movement' },
    { id: 'ch_cp_13', name: 'Band Resisted Push-Ups', type: 'Compound movement' },
    { id: 'ch_cp_14', name: 'Wide Grip Push-Ups', type: 'Compound movement' },
    { id: 'ch_cp_15', name: 'Hex Press', type: 'Compound movement' },
    { id: 'ch_is_1', name: 'Cable Crossovers', type: 'Isolated movement' },
    { id: 'ch_is_2', name: 'Low-to-High Cable Flyes', type: 'Isolated movement' },
    { id: 'ch_is_3', name: 'High-to-Low Cable Flyes', type: 'Isolated movement' },
    { id: 'ch_is_4', name: 'Svend Press', type: 'Isolated movement' },
    { id: 'ch_is_5', name: 'Machine Flyes', type: 'Isolated movement' },
    { id: 'ch_is_6', name: 'Single Arm Cable Flye', type: 'Isolated movement' },
    { id: 'ch_is_7', name: 'Around the Worlds', type: 'Isolated movement' },
    { id: 'ch_is_8', name: 'Plate Press', type: 'Isolated movement' },
    { id: 'ch_is_9', name: 'Stability Ball Push-Ups', type: 'Compound movement' },
    { id: 'ch_is_10', name: 'Archer Push-Ups', type: 'Compound movement' }
  ],
  BACK: [
    { id: 'lat_wide', name: 'Wide-Grip Lat Pulldown', type: 'Compound movement' },
    { id: 'lat_close', name: 'Close-Grip Lat Pulldown', type: 'Compound movement' },
    { id: 'lat_rev', name: 'Reverse-Grip Lat Pulldown (Underhand)', type: 'Compound movement' },
    { id: 'lat_vbar', name: 'Neutral-Grip Lat Pulldown (V-Bar)', type: 'Compound movement' },
    { id: 'bk_cp_1', name: 'Conventional Barbell Row', type: 'Compound movement' },
    { id: 'bk_cp_2', name: 'Pendlay Rows', type: 'Compound movement' },
    { id: 'bk_cp_3', name: 'T-Bar Rows', type: 'Compound movement' },
    { id: 'bk_cp_4', name: 'V-Bar Seated Row', type: 'Compound movement' },
    { id: 'bk_cp_5', name: 'Wide Grip Lat Pulldown (Behind Neck)', type: 'Compound movement' },
    { id: 'bk_cp_6', name: 'Close Grip Lat Pulldown', type: 'Compound movement' },
    { id: 'bk_cp_7', name: 'V-Bar Pulldown', type: 'Compound movement' },
    { id: 'bk_cp_8', name: 'Pull-Ups', type: 'Compound movement' },
    { id: 'bk_cp_9', name: 'Weighted Pull-Ups', type: 'Compound movement' },
    { id: 'bk_cp_10', name: 'Chin-Ups', type: 'Compound movement' },
    { id: 'bk_cp_11', name: 'Single-Arm Dumbbell Row', type: 'Compound movement' },
    { id: 'bk_cp_12', name: 'Chest-Supported Dumbbell Row', type: 'Compound movement' },
    { id: 'bk_cp_13', name: 'Machine Row', type: 'Compound movement' },
    { id: 'bk_cp_14', name: 'Rack Pulls', type: 'Compound movement' },
    { id: 'bk_cp_15', name: 'Meadows Row', type: 'Compound movement' },
    { id: 'bk_cp_16', name: 'Inverted Rows', type: 'Compound movement' },
    { id: 'bk_cp_17', name: 'Renegade Row', type: 'Compound movement' },
    { id: 'bk_cp_18', name: 'Seal Row', type: 'Compound movement' },
    { id: 'bk_cp_19', name: 'Yates Row', type: 'Compound movement' },
    { id: 'bk_cp_20', name: 'Kroc Row', type: 'Compound movement' },
    { id: 'bk_is_1', name: 'Straight Arm Pulldown', type: 'Isolated movement' },
    { id: 'bk_is_2', name: 'Reverse Pec Deck', type: 'Isolated movement' },
    { id: 'bk_is_3', name: 'Rope Pullovers', type: 'Isolated movement' },
    { id: 'bk_is_4', name: 'Hyperextensions', type: 'Isolated movement' },
    { id: 'bk_is_5', name: 'Good Mornings', type: 'Compound movement' },
    { id: 'bk_is_6', name: 'Barbell Shrugs', type: 'Isolated movement' },
    { id: 'bk_is_7', name: 'Dumbbell Shrugs', type: 'Isolated movement' },
    { id: 'bk_is_8', name: 'Machine Shrugs', type: 'Isolated movement' }
  ],
  SHOULDERS: [
    { id: 'sh_cp_1', name: 'Seated Dumbbell Press', type: 'Compound movement' },
    { id: 'sh_cp_2', name: 'Arnold Press', type: 'Compound movement' },
    { id: 'sh_cp_3', name: 'Push Press', type: 'Compound movement' },
    { id: 'sh_cp_4', name: 'Upright Rows', type: 'Compound movement' },
    { id: 'sh_cp_5', name: 'Z Press', type: 'Compound movement' },
    { id: 'sh_cp_6', name: 'Landmine Press', type: 'Compound movement' },
    { id: 'sh_cp_7', name: 'Bradford Press', type: 'Compound movement' },
    { id: 'sh_cp_8', name: 'Seated Barbell Press', type: 'Compound movement' },
    { id: 'sh_cp_9', name: 'Smith Machine Shoulder Press', type: 'Compound movement' },
    { id: 'sh_cp_10', name: 'Pike Push-Ups', type: 'Compound movement' },
    { id: 'sh_cp_11', name: 'Handstand Push-Ups', type: 'Compound movement' },
    { id: 'sh_cp_12', name: 'Kettlebell Press', type: 'Compound movement' },
    { id: 'sh_is_1', name: 'Cable Lateral Raises', type: 'Isolated movement' },
    { id: 'sh_is_2', name: 'Machine Lateral Raises', type: 'Isolated movement' },
    { id: 'sh_is_3', name: 'Front Raises', type: 'Isolated movement' },
    { id: 'sh_is_4', name: 'Barbell Front Raises', type: 'Isolated movement' },
    { id: 'sh_is_5', name: 'Cable Front Raises', type: 'Isolated movement' },
    { id: 'sh_is_6', name: 'Reverse Dumbbell Flyes', type: 'Isolated movement' },
    { id: 'sh_is_7', name: 'Machine Rear Delt Flyes', type: 'Isolated movement' },
    { id: 'sh_is_8', name: 'Cable Rear Delt Flyes', type: 'Isolated movement' },
    { id: 'sh_is_9', name: 'Face Pulls', type: 'Compound movement' },
    { id: 'sh_is_10', name: 'Leaning Lateral Raises', type: 'Isolated movement' },
    { id: 'sh_is_11', name: 'Y-Raises', type: 'Isolated movement' },
    { id: 'sh_is_12', name: 'Plate Front Raises', type: 'Isolated movement' },
    { id: 'sh_is_13', name: 'Egyptian Lateral Raises', type: 'Isolated movement' },
    { id: 'sh_is_14', name: 'Crucifix Holds', type: 'Isolated movement' },
    { id: 'sh_is_15', name: 'Front Plate Bus Drivers', type: 'Isolated movement' }
  ],
  BICEPS: [
    { id: 'bi_1', name: 'Barbell Curl', type: 'Isolated movement' },
    { id: 'bi_2', name: 'EZ Bar Curl', type: 'Isolated movement' },
    { id: 'bi_3', name: 'Dumbbell Alternate Curl', type: 'Isolated movement' },
    { id: 'bi_4', name: 'Incline Dumbbell Curl', type: 'Isolated movement' },
    { id: 'bi_5', name: 'Preacher Curl', type: 'Isolated movement' },
    { id: 'bi_6', name: 'Machine Preacher Curl', type: 'Isolated movement' },
    { id: 'bi_7', name: 'Hammer Curls', type: 'Isolated movement' },
    { id: 'bi_8', name: 'Cross-Body Hammer Curls', type: 'Isolated movement' },
    { id: 'bi_9', name: 'Cable Curls', type: 'Isolated movement' },
    { id: 'bi_10', name: 'Rope Cable Curls', type: 'Isolated movement' },
    { id: 'bi_11', name: 'High Cable Curls', type: 'Isolated movement' },
    { id: 'bi_12', name: 'Reverse Barbell Curls', type: 'Isolated movement' },
    { id: 'bi_13', name: 'Reverse Cable Curls', type: 'Isolated movement' },
    { id: 'bi_14', name: 'Concentration Curls', type: 'Isolated movement' },
    { id: 'bi_15', name: 'Spider Curls', type: 'Isolated movement' },
    { id: 'bi_16', name: 'Drag Curls', type: 'Isolated movement' },
    { id: 'bi_17', name: 'Zottman Curls', type: 'Isolated movement' },
    { id: 'bi_18', name: 'Cheat Curls', type: 'Compound movement' },
    { id: 'bi_19', name: 'Waiter Curls', type: 'Isolated movement' },
    { id: 'bi_20', name: 'Bayesian Curls', type: 'Isolated movement' },
    { id: 'bi_21', name: 'Bicep 21s', type: 'Isolated movement' },
    { id: 'bi_22', name: 'Lying Cable Curls', type: 'Isolated movement' },
    { id: 'bi_23', name: 'Seated Machine Curl', type: 'Isolated movement' },
    { id: 'bi_24', name: 'Single Arm Cable Curl', type: 'Isolated movement' },
    { id: 'bi_25', name: 'Static Hold Curls', type: 'Isolated movement' },
    { id: 'bi_26', name: 'Band Curls', type: 'Isolated movement' },
    { id: 'bi_27', name: 'Kettlebell Curls', type: 'Isolated movement' },
    { id: 'bi_28', name: 'Strict Wall Curls', type: 'Isolated movement' },
    { id: 'bi_29', name: 'Wide Grip Barbell Curl', type: 'Isolated movement' },
    { id: 'bi_30', name: 'Close Grip Barbell Curl', type: 'Isolated movement' }
  ],
  TRICEPS: [
    { id: 'tr_1', name: 'Close Grip Bench Press', type: 'Compound movement' },
    { id: 'tr_2', name: 'Tricep Dips', type: 'Compound movement' },
    { id: 'tr_3', name: 'Bench Dips', type: 'Compound movement' },
    { id: 'tr_4', name: 'Skullcrushers', type: 'Isolated movement' },
    { id: 'tr_5', name: 'EZ Bar Lying Tricep Extension', type: 'Isolated movement' },
    { id: 'tr_6', name: 'Dumbbell Overhead Extension', type: 'Isolated movement' },
    { id: 'tr_7', name: 'Single Arm Overhead Extension', type: 'Isolated movement' },
    { id: 'tr_8', name: 'Cable Pushdowns (Straight Bar)', type: 'Isolated movement' },
    { id: 'tr_9', name: 'Cable Pushdowns (Rope)', type: 'Isolated movement' },
    { id: 'tr_10', name: 'V-Bar Pushdowns', type: 'Isolated movement' },
    { id: 'tr_11', name: 'Reverse Grip Pushdowns', type: 'Isolated movement' },
    { id: 'tr_12', name: 'Dumbbell Kickbacks', type: 'Isolated movement' },
    { id: 'tr_13', name: 'Cable Kickbacks', type: 'Isolated movement' },
    { id: 'tr_14', name: 'Tate Press', type: 'Isolated movement' },
    { id: 'tr_15', name: 'JM Press', type: 'Compound movement' },
    { id: 'tr_16', name: 'Machine Tricep Extension', type: 'Isolated movement' },
    { id: 'tr_17', name: 'Overhead Cable Extension', type: 'Isolated movement' },
    { id: 'tr_18', name: 'French Press', type: 'Isolated movement' },
    { id: 'tr_19', name: 'Floor Tricep Extensions', type: 'Isolated movement' },
    { id: 'tr_20', name: 'Diamond Push-Ups', type: 'Compound movement' },
    { id: 'tr_21', name: 'Band Pushdowns', type: 'Isolated movement' },
    { id: 'tr_22', name: 'Cross-face Extensions', type: 'Isolated movement' },
    { id: 'tr_23', name: 'Sphinx Push-Ups', type: 'Compound movement' },
    { id: 'tr_24', name: 'Board Press', type: 'Compound movement' },
    { id: 'tr_25', name: 'Pin Press', type: 'Compound movement' },
    { id: 'tr_26', name: 'PJR Pullover', type: 'Isolated movement' },
    { id: 'tr_27', name: 'Katana Extensions', type: 'Isolated movement' },
    { id: 'tr_28', name: 'Tricep Press Machine', type: 'Compound movement' },
    { id: 'tr_29', name: 'Single Arm Reverse Pushdown', type: 'Isolated movement' },
    { id: 'tr_30', name: 'Overhead Rope Extensions', type: 'Isolated movement' }
  ],
  QUADS: [
    { id: 'qu_1', name: 'Front Squats', type: 'Compound movement' },
    { id: 'qu_2', name: 'Box Squats', type: 'Compound movement' },
    { id: 'qu_3', name: 'Pause Squats', type: 'Compound movement' },
    { id: 'qu_4', name: 'Leg Press', type: 'Compound movement' },
    { id: 'qu_5', name: 'Hack Squat', type: 'Compound movement' },
    { id: 'qu_6', name: 'Machine Hack Squat', type: 'Compound movement' },
    { id: 'qu_7', name: 'Goblet Squats', type: 'Compound movement' },
    { id: 'qu_8', name: 'Bulgarian Split Squats', type: 'Compound movement' },
    { id: 'qu_9', name: 'Dumbbell Lunges', type: 'Compound movement' },
    { id: 'qu_10', name: 'Walking Lunges', type: 'Compound movement' },
    { id: 'qu_11', name: 'Reverse Lunges', type: 'Compound movement' },
    { id: 'qu_12', name: 'Forward Lunges', type: 'Compound movement' },
    { id: 'qu_13', name: 'Single Leg Extensions', type: 'Isolated movement' },
    { id: 'qu_14', name: 'Sissy Squats', type: 'Isolated movement' },
    { id: 'qu_15', name: 'Pistol Squats', type: 'Compound movement' },
    { id: 'qu_16', name: 'Dumbbell Step-Ups', type: 'Compound movement' },
    { id: 'qu_17', name: 'Safety Bar Squats', type: 'Compound movement' },
    { id: 'qu_18', name: 'Front Foot Elevated Split Squats', type: 'Compound movement' },
    { id: 'qu_19', name: 'Cyclist Squats', type: 'Compound movement' },
    { id: 'qu_20', name: 'Belt Squats', type: 'Compound movement' },
    { id: 'qu_21', name: 'Landmine Squats', type: 'Compound movement' },
    { id: 'qu_22', name: 'Spanish Squats', type: 'Compound movement' },
    { id: 'qu_23', name: 'Jump Squats', type: 'Compound movement' },
    { id: 'qu_24', name: 'Wall Sits', type: 'Isolated movement' },
    { id: 'qu_25', name: 'Heel Elevated Trap Bar Deadlift', type: 'Compound movement' },
    { id: 'qu_26', name: 'Zercher Squats', type: 'Compound movement' },
    { id: 'qu_27', name: 'Narrow Stance Leg Press', type: 'Compound movement' },
    { id: 'qu_28', name: 'Pendulum Squat', type: 'Compound movement' },
    { id: 'qu_29', name: 'Sissy Squat Machine', type: 'Isolated movement' },
    { id: 'qu_30', name: 'V-Squat', type: 'Compound movement' }
  ],
  HAMSTRINGS: [
    { id: 'ha_1', name: 'Romanian Deadlift (RDL)', type: 'Compound movement' },
    { id: 'ha_2', name: 'Stiff-Legged Deadlift', type: 'Compound movement' },
    { id: 'ha_3', name: 'Dumbbell RDL', type: 'Compound movement' },
    { id: 'ha_4', name: 'Single-Leg RDL', type: 'Compound movement' },
    { id: 'ha_5', name: 'Lying Leg Curls', type: 'Isolated movement' },
    { id: 'ha_6', name: 'Seated Leg Curls', type: 'Isolated movement' },
    { id: 'ha_7', name: 'Standing Single Leg Curl', type: 'Isolated movement' },
    { id: 'ha_8', name: 'Nordic Hamstring Curls', type: 'Isolated movement' },
    { id: 'ha_9', name: 'Glute-Ham Raise (GHR)', type: 'Compound movement' },
    { id: 'ha_10', name: 'Good Mornings', type: 'Compound movement' },
    { id: 'ha_11', name: 'Cable Pull-Throughs', type: 'Compound movement' },
    { id: 'ha_12', name: 'Sliding Leg Curls', type: 'Isolated movement' },
    { id: 'ha_13', name: 'Swiss Ball Leg Curls', type: 'Isolated movement' },
    { id: 'ha_14', name: 'Kettlebell Swings', type: 'Compound movement' },
    { id: 'ha_15', name: 'Sumo Deadlift', type: 'Compound movement' },
    { id: 'ha_16', name: 'Trap Bar Deadlift', type: 'Compound movement' },
    { id: 'ha_17', name: 'Deficit Deadlift', type: 'Compound movement' },
    { id: 'ha_18', name: 'Machine RDL', type: 'Compound movement' },
    { id: 'ha_19', name: 'Banded Leg Curls', type: 'Isolated movement' },
    { id: 'ha_20', name: 'Inverse Curls', type: 'Isolated movement' },
    { id: 'ha_21', name: 'Dumbbell Lying Leg Curls', type: 'Isolated movement' },
    { id: 'ha_22', name: 'Elevated Hamstring Bridges', type: 'Isolated movement' },
    { id: 'ha_23', name: 'Reverse Hypers', type: 'Compound movement' },
    { id: 'ha_24', name: 'B-Stance RDL', type: 'Compound movement' },
    { id: 'ha_25', name: 'Cable Leg Curls', type: 'Isolated movement' },
    { id: 'ha_26', name: 'TRX Hamstring Curls', type: 'Isolated movement' },
    { id: 'ha_27', name: 'Glider Hamstring Curls', type: 'Isolated movement' },
    { id: 'ha_28', name: 'Razor Curls', type: 'Isolated movement' },
    { id: 'ha_29', name: 'Hip Extensions', type: 'Isolated movement' },
    { id: 'ha_30', name: 'Back Extensions (Hamstring Focus)', type: 'Isolated movement' }
  ],
  GLUTES: [
    { id: 'gl_1', name: 'Barbell Hip Thrusts', type: 'Compound movement' },
    { id: 'gl_2', name: 'Dumbbell Hip Thrusts', type: 'Compound movement' },
    { id: 'gl_3', name: 'Machine Hip Thrusts', type: 'Compound movement' },
    { id: 'gl_4', name: 'Single-Leg Hip Thrusts', type: 'Compound movement' },
    { id: 'gl_5', name: 'Glute Bridges', type: 'Isolated movement' },
    { id: 'gl_6', name: 'Weighted Glute Bridges', type: 'Isolated movement' },
    { id: 'gl_7', name: 'Frog Pumps', type: 'Isolated movement' },
    { id: 'gl_8', name: 'Cable Pull-Throughs', type: 'Compound movement' },
    { id: 'gl_9', name: 'Cable Glute Kickbacks', type: 'Isolated movement' },
    { id: 'gl_10', name: 'Machine Glute Kickbacks', type: 'Isolated movement' },
    { id: 'gl_11', name: 'Banded Kickbacks', type: 'Isolated movement' },
    { id: 'gl_12', name: 'Fire Hydrants', type: 'Isolated movement' },
    { id: 'gl_13', name: 'Machine Abductions', type: 'Isolated movement' },
    { id: 'gl_14', name: 'Seated Band Abductions', type: 'Isolated movement' },
    { id: 'gl_15', name: 'Cable Side Kicks', type: 'Isolated movement' },
    { id: 'gl_16', name: 'Deficit Reverse Lunges', type: 'Compound movement' },
    { id: 'gl_17', name: 'Curtsy Lunges', type: 'Compound movement' },
    { id: 'gl_18', name: 'Bulgarian Split Squats (Glute Focus)', type: 'Compound movement' },
    { id: 'gl_19', name: 'Step Downs', type: 'Compound movement' },
    { id: 'gl_20', name: 'Kass Glute Press', type: 'Compound movement' },
    { id: 'gl_21', name: 'Reverse Hyperextensions', type: 'Compound movement' },
    { id: 'gl_22', name: '45-Degree Hyperextensions', type: 'Isolated movement' },
    { id: 'gl_23', name: 'B-Stance Hip Thrust', type: 'Compound movement' },
    { id: 'gl_24', name: 'Smith Machine Donkey Kicks', type: 'Isolated movement' },
    { id: 'gl_25', name: 'Clamshells', type: 'Isolated movement' },
    { id: 'gl_26', name: 'Weighted Clamshells', type: 'Isolated movement' },
    { id: 'gl_27', name: 'Lateral Band Walks', type: 'Isolated movement' },
    { id: 'gl_28', name: 'Monster Walks', type: 'Isolated movement' },
    { id: 'gl_29', name: 'Sumo Squats', type: 'Compound movement' },
    { id: 'gl_30', name: 'Kettlebell Swings', type: 'Compound movement' }
  ],
  CALVES: [
    { id: 'ca_1', name: 'Standing Barbell Calf Raise', type: 'Isolated movement' },
    { id: 'ca_2', name: 'Standing Dumbbell Calf Raise', type: 'Isolated movement' },
    { id: 'ca_3', name: 'Standing Machine Calf Raise', type: 'Isolated movement' },
    { id: 'ca_4', name: 'Seated Calf Raise Machine', type: 'Isolated movement' },
    { id: 'ca_5', name: 'Seated Barbell Calf Raise', type: 'Isolated movement' },
    { id: 'ca_6', name: 'Donkey Calf Raises', type: 'Isolated movement' },
    { id: 'ca_7', name: 'Leg Press Calf Raises', type: 'Isolated movement' },
    { id: 'ca_8', name: 'Single-Leg Calf Raises', type: 'Isolated movement' },
    { id: 'ca_9', name: 'Smith Machine Calf Raises', type: 'Isolated movement' },
    { id: 'ca_10', name: 'Box Jumps', type: 'Compound movement' },
    { id: 'ca_11', name: 'Jump Rope', type: 'Compound movement' },
    { id: 'ca_12', name: 'Tibialis Raises', type: 'Isolated movement' },
    { id: 'ca_13', name: 'Wall Calf Stretches', type: 'Isolated movement' },
    { id: 'ca_14', name: 'Farmer\'s Walk on Toes', type: 'Compound movement' },
    { id: 'ca_15', name: 'Stair Calf Raises', type: 'Isolated movement' },
    { id: 'ca_16', name: 'Elevated Calf Raises', type: 'Isolated movement' },
    { id: 'ca_17', name: 'Banded Calf Raises', type: 'Isolated movement' },
    { id: 'ca_18', name: 'Seated Dumbbell Calf Raises', type: 'Isolated movement' },
    { id: 'ca_19', name: 'Hack Squat Calf Raises', type: 'Isolated movement' },
    { id: 'ca_20', name: 'Eccentric Calf Drops', type: 'Isolated movement' },
    { id: 'ca_21', name: 'Sled Pushes', type: 'Compound movement' },
    { id: 'ca_22', name: 'Agility Ladder Drills', type: 'Compound movement' },
    { id: 'ca_23', name: 'Pogo Jumps', type: 'Compound movement' },
    { id: 'ca_24', name: 'Squat Hold Calf Raises', type: 'Isolated movement' },
    { id: 'ca_25', name: 'Lunge Position Calf Raises', type: 'Isolated movement' },
    { id: 'ca_26', name: 'Calf Jumps', type: 'Compound movement' },
    { id: 'ca_27', name: 'Rocking Calf Raises', type: 'Isolated movement' },
    { id: 'ca_28', name: 'Reverse Calf Raises', type: 'Isolated movement' },
    { id: 'ca_29', name: 'Barefoot Running (Treadmill)', type: 'Compound movement' },
    { id: 'ca_30', name: 'Cable Calf Raises', type: 'Isolated movement' }
  ],
  ABS: [
    { id: 'ab_1', name: 'Crunches', type: 'Isolated movement' },
    { id: 'ab_2', name: 'Bicycle Crunches', type: 'Isolated movement' },
    { id: 'ab_3', name: 'Reverse Crunches', type: 'Isolated movement' },
    { id: 'ab_4', name: 'Sit-Ups', type: 'Compound movement' },
    { id: 'ab_5', name: 'Decline Sit-Ups', type: 'Compound movement' },
    { id: 'ab_6', name: 'Hanging Leg Raises', type: 'Compound movement' },
    { id: 'ab_7', name: 'Hanging Knee Raises', type: 'Compound movement' },
    { id: 'ab_8', name: 'Captain\'s Chair Leg Raises', type: 'Isolated movement' },
    { id: 'ab_9', name: 'Lying Leg Raises', type: 'Isolated movement' },
    { id: 'ab_10', name: 'Flutter Kicks', type: 'Isolated movement' },
    { id: 'ab_11', name: 'Scissor Kicks', type: 'Isolated movement' },
    { id: 'ab_12', name: 'Russian Twists', type: 'Isolated movement' },
    { id: 'ab_13', name: 'Weighted Russian Twists', type: 'Isolated movement' },
    { id: 'ab_14', name: 'Cable Crunches', type: 'Isolated movement' },
    { id: 'ab_15', name: 'Machine Crunches', type: 'Isolated movement' },
    { id: 'ab_16', name: 'Ab Wheel Rollouts', type: 'Compound movement' },
    { id: 'ab_17', name: 'Plank', type: 'Isolated movement' },
    { id: 'ab_18', name: 'Side Plank', type: 'Isolated movement' },
    { id: 'ab_19', name: 'Weighted Plank', type: 'Isolated movement' },
    { id: 'ab_20', name: 'Hollow Body Hold', type: 'Isolated movement' },
    { id: 'ab_21', name: 'V-Ups', type: 'Compound movement' },
    { id: 'ab_22', name: 'Tuck Jumps', type: 'Compound movement' },
    { id: 'ab_23', name: 'Mountain Climbers', type: 'Compound movement' },
    { id: 'ab_24', name: 'Woodchoppers', type: 'Compound movement' },
    { id: 'ab_25', name: 'Cable Pallof Press', type: 'Isolated movement' },
    { id: 'ab_26', name: 'Dead Bugs', type: 'Isolated movement' },
    { id: 'ab_27', name: 'Windshield Wipers', type: 'Isolated movement' },
    { id: 'ab_28', name: 'Toes to Bar', type: 'Compound movement' },
    { id: 'ab_29', name: 'Swiss Ball Crunches', type: 'Isolated movement' },
    { id: 'ab_30', name: 'Dragon Flags', type: 'Compound movement' }
  ],
  FOREARMS: [
    { id: 'fo_1', name: 'Barbell Wrist Curls', type: 'Isolated movement' },
    { id: 'fo_2', name: 'Dumbbell Wrist Curls', type: 'Isolated movement' },
    { id: 'fo_3', name: 'Reverse Barbell Wrist Curls', type: 'Isolated movement' },
    { id: 'fo_4', name: 'Reverse Dumbbell Wrist Curls', type: 'Isolated movement' },
    { id: 'fo_5', name: 'Behind the Back Barbell Wrist Curls', type: 'Isolated movement' },
    { id: 'fo_6', name: 'Farmer\'s Walks', type: 'Compound movement' },
    { id: 'fo_7', name: 'Dead Hangs', type: 'Isolated movement' },
    { id: 'fo_8', name: 'Fat Gripz Holds', type: 'Isolated movement' },
    { id: 'fo_9', name: 'Plate Pinches', type: 'Isolated movement' },
    { id: 'fo_10', name: 'Towel Pull-Ups', type: 'Compound movement' },
    { id: 'fo_11', name: 'Rope Climbs', type: 'Compound movement' },
    { id: 'fo_12', name: 'Zottman Curls', type: 'Compound movement' },
    { id: 'fo_13', name: 'Reverse Curls', type: 'Compound movement' },
    { id: 'fo_14', name: 'Hammer Curls', type: 'Compound movement' },
    { id: 'fo_15', name: 'Reverse Cable Curls', type: 'Isolated movement' },
    { id: 'fo_16', name: 'Wrist Rollers', type: 'Isolated movement' },
    { id: 'fo_17', name: 'Gripper Squeezes', type: 'Isolated movement' },
    { id: 'fo_18', name: 'Hex Head Dumbbell Holds', type: 'Isolated movement' },
    { id: 'fo_19', name: 'Pinch Grip Deadlifts', type: 'Compound movement' },
    { id: 'fo_20', name: 'Thick Bar Deadlifts', type: 'Compound movement' },
    { id: 'fo_21', name: 'Kettlebell Bottoms-Up Press', type: 'Compound movement' },
    { id: 'fo_22', name: 'Pronation/Supination with Dumbbell', type: 'Isolated movement' },
    { id: 'fo_23', name: 'Sledgehammer Levers', type: 'Isolated movement' },
    { id: 'fo_24', name: 'Rice Bucket Digs', type: 'Isolated movement' },
    { id: 'fo_25', name: 'Finger Curls', type: 'Isolated movement' },
    { id: 'fo_26', name: 'Cable Wrist Curls', type: 'Isolated movement' },
    { id: 'fo_27', name: 'Reverse Machine Wrist Curls', type: 'Isolated movement' },
    { id: 'fo_28', name: 'Fingertip Push-Ups', type: 'Compound movement' },
    { id: 'fo_29', name: 'Weighted Holds', type: 'Isolated movement' },
    { id: 'fo_30', name: 'Static Barbell Holds', type: 'Isolated movement' }
  ]
};
